---
title: "ggplot example"
author: "Sam Wozniak"
date: "March 6, 2018"
output:
  html_document: default
  pdf_document: default
---
The following models/graphs were created for a homework problem in ST516. This example uses the 'barnacle' dataset from the package 'npregfast'. The dataset supplies ~2000 observations of barnacles with the following data for each observation: rostro-carinal length (mm)--'RC', the dry weight (g)--'DW', and the harvest location--'F'.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(npregfast)
```

```{r}
#subsetting barnacle data because model (below) doesn't take values of 0
sub_b <- subset(barnacle, DW > 0)
str(sub_b)

#create model
#ifelse -> two different models depending on harvest location (level of sub_b$F)
m <- nls(DW ~ exp(ifelse(F == 'barca', t1 + t2*log(RC), t3 + t4*log(RC))), data = sub_b,
         start = c(t1 = -8.17, t2 = 2.89, t3 = -8.17, t4 = 2.89))

#change levels of sub_b$F from "barca" and "lens" to more descriptive names for plotting 
levels(sub_b$F) <- c("Punta de la Barca Tidal Zone", "Punta Lens Tidal Zone")

#create dataframe with predicted values (from model) for plotting
d <- expand.grid(RC = seq(2.5,25, length = 100), 
                 F = c("Punta de la Barca Tidal Zone", "Punta Lens Tidal Zone"))
d$yhat <- predict(m, newdata = d)

#plot original data and model
p <- ggplot(sub_b, aes(x = RC, y = DW))
p <- p + geom_point(alpha = 0.25) 
p <- p + facet_wrap(~F)  
p <- p + theme_bw()
p <- p + geom_line(aes(y = yhat), data = d, color = 'red')
p <- p + labs(title = "Barnacle Dry Weight by Length and Harvest Location", 
              y = "Dry Weight (g)", 
              x = "Length (mm)")
plot(p)
```
