---
title: "Data Cleaning Practice"
author: "Matthew R. Dunkle"
date: "2/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=F, message=F, warning = F}
#setup
setwd("/Users/matthewrdunkle/Documents/GitHub/REM504-DataScience/Practice_Datasets/student_data")
mydata=readxl::read_xlsx("Dunkle_Mesocosm_PeriphytonData.xlsx")
head(mydata)
```

Pulling out just the part of this that has the dry weight and ashed weight information.
```{r, echo=F, message=F, warning = F}
mydata_AFDM = mydata[5:23, 7:11]
mydata_AFDM
```
Adding column names
```{r, echo=F, message=F, warning = F}
colnames(mydata_AFDM) = c("Tank","Dark_Dry","Dark_Ashed","Light_Dry","Light_Ashed")
mydata_AFDM
```

```{r, echo=F, message=F, warning = F}
mydata_filtermass = mydata[2:47, 13:15]
colnames(mydata_filtermass) = c("RefNum","Mass","FilterSize")
mydata_filtermass
```

```{r, echo=F, message=F, warning = F}
library(reshape2)

mydata_filterkey = mydata[5:22,1:5]
colnames(mydata_filterkey) = c("Tank","Dark_AFDM","Dark_ChlA","Light_AFDM","Light_ChlA")
mydata_filterkey

mydata_filterkey_dark = mydata_filterkey[1:18, 1:3]
#mydata_filterkey_dark$Tank = as.factor(c("Tank1","Tank2","Tank3","Tank4","Tank5","Tank6","Tank7","Tank8","Tank9","Tank10","Tank11","Tank12","Tank13","Tank14","Tank15","Tank16","Tank17","Tank18"))
mydata_filterkey_dark = gather(mydata_filterkey_dark, "Treatment","FilterNo",2:3)
mydata_filterkey_dark
```

```{r, echo=F, message=F, warning = F}
mydata_filterkey_light = mydata_filterkey[1:18, c(1,4:5)]
mydata_filterkey_light = gather(mydata_filterkey_light, "Treatment","FilterNo",2:3)
mydata_filterkey_light
```

```{r, echo=F, message=F, warning = F}
mydata_filterkey_long = rbind(mydata_filterkey_dark, mydata_filterkey_light)
n=36
mydata_filterkey_long$TreatmentA = c(rep("Dark", times = n), rep("Light", times = n))
TreatmentB = c("Trout","Lamprey","Trout","Lamprey","Lamprey","Trout","Trout","Control","Trout","Lamprey","Control","Control","Lamprey","Control","Trout","Control","Control","Lamprey")
mydata_filterkey_long$TreatmentB = rep(TreatmentB, times=4)
mydata_filterkey_long = mydata_filterkey_long[-2]
```

```{r, echo=F, message=F, warning = F}
mydata_AFDM_dark = mydata_AFDM [1:18, 1:3]
mydata_AFDM_dark$TreatmentA = rep("Dark", times = 18)
colnames(mydata_AFDM_dark) = c("Tank","DryMass","AshedMass","TreatmentA")
  
mydata_AFDM_light = mydata_AFDM [1:18, c(1, 4:5)]
mydata_AFDM_light$TreatmentA = rep("Light", times = 18)
colnames(mydata_AFDM_light) = c("Tank","DryMass","AshedMass","TreatmentA")
mydata_AFDM_long = rbind(mydata_AFDM_dark, mydata_AFDM_light)
mydata_AFDM_long$TreatmentB = 
```
