---
title: "Tidying Data"
output:
  html_document:
    df_print: paged
    
---

```{r setup}
install.packages("dplyr", "tidyr")
library(dplyr, tidyr)
setwd("U:/My IDEA Documents/REM 429/HarLite lab/R")
```
#Alex tries to figure this out
## Importing Data and combining into one data frame
```{r}

buffer <- read.csv("buffer.csv", header = F, skip = 2)
config <- read.csv("config.csv", header = F, skip = 2)
harvest <- read.csv("harvest.csv", header = F, skip = 2)
percent <- read.csv("percent.csv", header = F, skip = 2)
persist <- read.csv("persistence.csv", header = F, skip = 2)
#Config has one extra row so need to alter
har.data <-bind_cols(buffer,harvest,percent,persist) 
har.data[28,] <- "NA" # ADD NAs
har.data <- bind_cols(har.data, config)
rm(buffer,config, harvest, percent, persist)
```

## Using dplyr to make the data tidy

```{r}
??gather
??spread
??separate
??mutate
??unite

har.data <- har.data[-c(6:22,25),] # drop empty and useless rows

har.data2 <- gather(har.data, "key", "value")

har.data3 <- separate(data = har.data2, col = value, sep =": ", into = c("Variable", "Value"))

# Regular expressions!
har.data3$Variable <- gsub("\\s\\d\\d\\d\\s", "=", har.data3$Variable)

har.data4 <- separate(data = har.data3, col = Variable, sep = "=", into = c("Variable", "Value2"))

# Some witchcraft from stackoverflow...to merge away the NAs
har.data4$Value[!is.na(har.data4$Value2)] = har.data4$Value2[!is.na(har.data4$Value2)]  
har.data4$Value2 <- NULL

har.data5 <- spread(har.data4, key = "Variable", value = "Value") 
names(har.data5)
har.data5$`<NA>` <- NULL

names(har.data5) <- c("Observation", "EdgeArea", "InteriorArea", "HarvestSize", "Buffer", "AllowableAge", "Persistence", "PercentCut", "DispMethod", "SdHarvest", "MeanPatchSize")

```

Now the data is at least realtively tidy i.e. each row is an observation, each column a variable. Now need to remove some of the text which is mix in with numerics

```{r}
rm(har.data, har.data2, har.data3, har.data4)
har.data5$EdgeArea <- gsub("hectares\\.", "", har.data5$EdgeArea)
har.data5$InteriorArea <- gsub("hectares\\.", "", har.data5$InteriorArea)
har.data5$EdgeArea <- as.numeric(har.data5$EdgeArea)      
har.data5$InteriorArea <- as.numeric(har.data5$InteriorArea) 
har.data5$Buffer <- gsub("\\. meters", "", har.data5$Buffer)

har.data5$PercentCut <- gsub("*\\(.*?\\)", "", har.data5$PercentCut)

# Change variables to numeric
for(i in c(2:8,10:ncol(har.data5))) {
    har.data5[,i] <- as.numeric(har.data5[,i])
}
har.data5$DispMethod <- as.factor(har.data5$DispMethod)

str(har.data5)
```

#NOW TO ACTUALLY ANALYSE THE DATA

## Stats
```{r}
buffer.data <- subset(har.data5,har.data5$PercentCut == 1.00 & har.data5$Buffer == 180 & har.data5$DispMethod=="DISPERSED" & har.data5$Persistence==2)
model1 <- lm (buffer.data$EdgeArea ~ log(buffer.data$HarvestSize)) # try log instead
summary(model1)
plot(model1) # relationship does not look linear
```

## Pretty graphics
```{r}
install.packages("ggplot2")
library(ggplot2)

g <- ggplot(data = subset(har.data5, har.data5$PercentCut == 1.00 & har.data5$Buffer == 180 & har.data5$DispMethod=="DISPERSED" & har.data5$Persistence==2), aes(x = HarvestSize))
g + geom_point(aes(y = EdgeArea))
g + geom_point(aes(y = InteriorArea)) + theme_classic() + geom_smooth(method = "lm", aes(y = InteriorArea))

f <- ggplot(data = har.data5, aes(y = MeanPatchSize), fill = DispMethod)
f <- f + geom_boxplot(aes(x = DispMethod, fill = DispMethod)) + theme_classic()
f
```



